### ISSUE TITLE
App crash onCreateOptionsMenu in LogBaseFragment when used in different dependency

### ISSUE THREAD

**Issue by SodaSurfer** [AppDevNext/Logcat#450]
Hello

I'm not using this library, but I see in my crashlytics logtrace this crash:
```
Fatal Exception: java.lang.NullPointerException: null cannot be cast to non-null type android.widget.CompoundButton
       at info.hannes.logcat.base.LogBaseFragment.onCreateOptionsMenu(LogBaseFragment.kt:151)
       at androidx.fragment.app.Fragment.performCreateOptionsMenu(Fragment.java:3237)
       at androidx.fragment.app.FragmentManager.dispatchCreateOptionsMenu(FragmentManager.java:3066)
       at androidx.fragment.app.FragmentManager$2.onCreateMenu(FragmentManager.java:480)
       at androidx.core.view.MenuHostHelper.onCreateMenu(MenuHostHelper.java:93)
       at androidx.activity.ComponentActivity.onCreatePanelMenu(ComponentActivity.java:522)
       at androidx.appcompat.view.WindowCallbackWrapper.onCreatePanelMenu(WindowCallbackWrapper.java:95)
       at androidx.appcompat.app.AppCompatDelegateImpl$AppCompatWindowCallback.onCreatePanelMenu(AppCompatDelegateImpl.java:3429)
       at androidx.appcompat.app.AppCompatDelegateImpl.preparePanel(AppCompatDelegateImpl.java:2027)
       at androidx.appcompat.app.AppCompatDelegateImpl.doInvalidatePanelMenu(AppCompatDelegateImpl.java:2313)
       at androidx.appcompat.app.AppCompatDelegateImpl$2.run(AppCompatDelegateImpl.java:278)
       at android.os.Handler.handleCallback(Handler.java:790)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6494)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Now, the only dependency that I use in my app that mybe related is:
`implementation 'com.github.hannesa2:paho.mqtt.android:3.3.5'`

is there a way to fix this issue?
as I don't use this library, I cannot preform any actions on it, and I still need the other library (`com.github.hannesa2:paho.mqtt.android:3.3.5`) which I assume uses this one.

maybe it worth to mention that I also don't have a menu and I dont have a 'onCreateOptionsMenu' or 'setOptionsMenu' anywhere on my app, so it also weird why this lib tries to invoke the 'onCreateOptionsMenu' method from the first place.

would appreciate any response about this issue, because I really don't see any situation on how I can fix this issue.

Thanks!

**Comment by hannesa2** [comment]
The rout cause is a missing option menu on your side.
<img width="717" alt="image" src="https://user-images.githubusercontent.com/3314607/218034433-4edbb86a-9d5e-4447-a2f5-ff82e6ebdae0.png">

Why using `3.3.5` and not a more recent one ? Sometimes after `3.3.5` there was split of logging and UI.
Please give a more recent version a try.

**Comment by SodaSurfer** [comment]
> The rout cause is a missing option menu on your side. <img alt="image" width="717" src="https://user-images.githubusercontent.com/3314607/218034433-4edbb86a-9d5e-4447-a2f5-ff82e6ebdae0.png">
> 
> Why using `com.github.hannesa2:paho.mqtt.android:3.3.5` and not a more recent one ? Sometimes after `3.3.5` there was split of logging and UI. Please give a more recent version a try.

thanks I'll upgrade my lib. I didn't see there was an upgrade.
by the way, indeed I don't use an option menu on my side I wanted to set it to null, but I don't think it should be a problem, or is it?

**Comment by hannesa2** [comment]
Hmm, I guess in a more recent version, there is still this issue. 
Can you share a **running** demo app, where this happens ? 
If yes, I can try to fix it, but **only with a running demo**

**Comment by SodaSurfer** [comment]
the app is not yet on production, therefore I cannot provide a demo, though isn't it possible to just add a null check on line 151 before casting to the CompundButton to solve it?
I guess it will be easier then to try and understand why the `onCreateOptionsMenu` is being called even though there is no option menu.
